<?php
/**
 * Implements hook_permission().
 */
function mmd_permission() {
  return array(
    'mmd' => array(
      'title' => t('MMD Setting'),
      'description' => t('Perform access'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mmd_menu() {
  $items = array();
  $items['mmd'] = array(
    'title' => t('MMD'),
    'description' => t('My.Module.D'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mmd_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'file' => 'mmd.form.inc',
  );

  $items['mmd/add'] = array(
    'title' => t('MMD INPUT'),
    'description' => t('Add new item'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mmd_form'),
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'mmd.form.inc',
  );

  $items['mmd/display'] = array(
    'title' => t('MMD view'),
    'description' => 'DMN custom module view',
    'page callback' => 'mmd_display',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'file' => 'mmd.display.inc',
  );

  $items['admin/config/content/mmd'] = array(
    'title' => 'MMD Configuration',
    'description' => 'MMD module configuration',
    'page callback' => 'mmd_admin_view_page',
    'access arguments' => array('mmd'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mmd.admin.inc',
  );

 return $items;
}