<?php
/**
 * Implements hook_permission().
 */
function mmd_permission() {
  return array(
    'mmd_access' => array(
      'title' => t('MMD access'),
      'description' => t('Perform access'),
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function mmd_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && !empty($plugin_type)) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function mmd_theme()
{
  return array(
    'mmd_display_item' => array(
      'template' => 'mmd_display_item',
      'arguments' => array(
        'title' => NULL,
        'data' => NULL,
        'created' => NULL,
        'img' => NULL,
        'importance' => NULL,
        'src_path' => NULL,
        'thumbnail_path' => NULL,
        'imp_img' => NULL,
        'row' => NULL,
        'read_more' => NULL,
      )
    )
  );
}

/**
 * Implements hook_menu().
 */
function mmd_menu() {
  $items = array();
  $items['mmd'] = array(
    'title' => t('MMD'),
    'description' => t('My.Module.D'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mmd_form'),
    'access arguments' => array('mmd_access'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'file' => 'mmd.form.inc',
  );
 return $items;
}